name: Locky
version: 1.0.0
author: UlvBror
main: com.ulvbror.locky.Locky
api-version: 1.14
commands:
  givelock:
    description: Gives the player a personal or team lock
    usage: /<command> [personal|team] <player>